# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fc78e153b523bb2a6e3c86971941d3e30057db937bc402258499ad20c062bfcf8ac3c0f9bfc704bfb26f095a36a3a7d9b465193ac1f762ea10c6dcaf13e4484

test:
  secret_key_base: 657ac08c00a4c61f60cb2445b8478dfbb58271288f545a98b407da80c6aeff4216501b23830352ff4fa6e9ec037f976f95d819a6a4881c01d8f0947cc6ab3050

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
